/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfazGrafica;

import CapaBL.PeliculasBL;
import Entidades.Peliculas;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Emma
 */
public class VentanaInternaDisponibilidadPeliculas extends javax.swing.JInternalFrame {

    PeliculasBL objPeliculasBL;
    private TableRowSorter trsFiltro;

    /**
     * Creates new form VentanaInternaDisponibilidadPeliculas
     */
    public VentanaInternaDisponibilidadPeliculas() throws Exception {
        initComponents();
        objPeliculasBL = new PeliculasBL();
        ConsultarRegistros();
    }

    private void ConsultarRegistros() throws Exception {
        try {
            tblDisponibilidad.setRowSorter(null);
            ArrayList<Peliculas> lista;
            lista = objPeliculasBL.Listado();

            if (lista != null) {

                String col[] = {"ID Pelicula", "Descripcion", "Genero", "Cantidad", "Estado"};

                DefaultTableModel tableModel = new DefaultTableModel(col, 0);

                tblDisponibilidad.setModel(tableModel);

                for (int i = 0; i < lista.size(); i++) {

                    int IDPelicula = lista.get(i).getIntIdPelicula();
                    String Descripcion = lista.get(i).getStrDescripcion();
                    String Genero = lista.get(i).getStrGenero();
                    int Cantidad = lista.get(i).getIntCantidadPeliculas();
                    String Estado = lista.get(i).getStrEstado();

                    Object[] data = {IDPelicula, Descripcion, Genero, Cantidad, Estado};

                    tableModel.addRow(data);
                }
            }
        } catch (Exception ex) {
            throw new Exception("Error en tabla");
        }

    }

    public void filtro() {
        int columnaABuscar = 0;
        if (Filtradobx.getSelectedItem() == "Descripción") {
            columnaABuscar = 1;
        }
        if (Filtradobx.getSelectedItem() == "Genero") {
            columnaABuscar = 2;
        }
        trsFiltro.setRowFilter(RowFilter.regexFilter(Busquedatxt.getText(), columnaABuscar));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDisponibilidad = new javax.swing.JTable();
        Buscarlbl = new javax.swing.JLabel();
        Filtradobx = new javax.swing.JComboBox<>();
        Busquedatxt = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Disponibilidad de Películas");

        tblDisponibilidad.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblDisponibilidad);

        Buscarlbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Buscarlbl.setText("Buscar");

        Filtradobx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Descripción", "Genero" }));

        Busquedatxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                BusquedatxtKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 739, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Buscarlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Filtradobx, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Busquedatxt, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Buscarlbl)
                    .addComponent(Filtradobx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Busquedatxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BusquedatxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BusquedatxtKeyTyped
        Busquedatxt.addKeyListener(new KeyAdapter() {
            @Override
            public void keyReleased(final KeyEvent e) {
                String cadena = (Busquedatxt.getText());
                Busquedatxt.setText(cadena);
                repaint();
                filtro();
            }
        });
        trsFiltro = new TableRowSorter(tblDisponibilidad.getModel());
        tblDisponibilidad.setRowSorter(trsFiltro);
    }//GEN-LAST:event_BusquedatxtKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Buscarlbl;
    private javax.swing.JTextField Busquedatxt;
    private javax.swing.JComboBox<String> Filtradobx;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDisponibilidad;
    // End of variables declaration//GEN-END:variables
}
