/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfazGrafica;

import Utilidades.AbrirVentanaUnica;
import Utilidades.ConfirmacionCerrarVentanas;
import Utilidades.FechaHora;
import Utilidades.HoraActual;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Emma
 */
public class VentanaMenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaMenuPrincipal
     */
    public VentanaMenuPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
        FechaHora objFechaHora = new FechaHora();
        Calendar calendario = Calendar.getInstance();
        Fechalbl.setText(objFechaHora.Fecha());
        HoraActual objHoraActual = new HoraActual();
        objHoraActual.setJl(Horalbl, Integer.parseInt(objFechaHora.HH()), Integer.parseInt(objFechaHora.MM()), Integer.parseInt(objFechaHora.SS()));
        objHoraActual.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        Horalbl = new javax.swing.JLabel();
        Fechalbl = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        IngresoClientes = new javax.swing.JMenu();
        IngresoRRHH = new javax.swing.JMenu();
        IngresoUsuarios = new javax.swing.JMenuItem();
        IngresoEmpleados = new javax.swing.JMenuItem();
        IngresoVacaciones = new javax.swing.JMenuItem();
        IngresoInventario = new javax.swing.JMenu();
        IngresoReservacion = new javax.swing.JMenu();
        IngresoHistorico = new javax.swing.JMenu();
        IngresoDisponibilidad = new javax.swing.JMenu();
        OpcionSalir = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Horalbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Horalbl.setForeground(new java.awt.Color(255, 255, 255));
        Horalbl.setText("00:00:00");

        Fechalbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Fechalbl.setForeground(new java.awt.Color(255, 255, 255));
        Fechalbl.setText("Fecha");

        jLabel4.setFont(new java.awt.Font("AR BERKLEY", 1, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Video ");

        jLabel3.setFont(new java.awt.Font("AR BERKLEY", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Hitokiri");

        jDesktopPane1.setLayer(Horalbl, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(Fechalbl, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap(511, Short.MAX_VALUE)
                .addComponent(Fechalbl, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Horalbl, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 259, Short.MAX_VALUE)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Horalbl, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Fechalbl, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        getContentPane().add(jDesktopPane1, java.awt.BorderLayout.CENTER);

        IngresoClientes.setText("Clientes");
        IngresoClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IngresoClientesMouseClicked(evt);
            }
        });
        jMenuBar1.add(IngresoClientes);

        IngresoRRHH.setText("RRHH");
        IngresoRRHH.setContentAreaFilled(false);
        IngresoRRHH.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        IngresoRRHH.setRolloverEnabled(false);

        IngresoUsuarios.setText("Usuarios");
        IngresoUsuarios.setFocusable(true);
        IngresoUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngresoUsuariosActionPerformed(evt);
            }
        });
        IngresoRRHH.add(IngresoUsuarios);

        IngresoEmpleados.setText("Empleados");
        IngresoEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngresoEmpleadosActionPerformed(evt);
            }
        });
        IngresoRRHH.add(IngresoEmpleados);

        IngresoVacaciones.setText("Vacaciones");
        IngresoVacaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngresoVacacionesActionPerformed(evt);
            }
        });
        IngresoRRHH.add(IngresoVacaciones);

        jMenuBar1.add(IngresoRRHH);

        IngresoInventario.setText("Inventario");
        IngresoInventario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IngresoInventarioMouseClicked(evt);
            }
        });
        jMenuBar1.add(IngresoInventario);

        IngresoReservacion.setText("Reservación");
        IngresoReservacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IngresoReservacionMouseClicked(evt);
            }
        });
        jMenuBar1.add(IngresoReservacion);

        IngresoHistorico.setText("Historico");
        IngresoHistorico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IngresoHistoricoMouseClicked(evt);
            }
        });
        jMenuBar1.add(IngresoHistorico);

        IngresoDisponibilidad.setText("Disponibilidad");
        IngresoDisponibilidad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IngresoDisponibilidadMouseClicked(evt);
            }
        });
        jMenuBar1.add(IngresoDisponibilidad);

        OpcionSalir.setText("Salir");
        OpcionSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OpcionSalirMouseClicked(evt);
            }
        });
        jMenuBar1.add(OpcionSalir);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OpcionSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OpcionSalirMouseClicked
        this.setDefaultCloseOperation(WIDTH);
        ConfirmacionCerrarVentanas objConfirmacionCerrarVentanas = new ConfirmacionCerrarVentanas();
        objConfirmacionCerrarVentanas.CerrarVentana();
    }//GEN-LAST:event_OpcionSalirMouseClicked

    private void IngresoClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IngresoClientesMouseClicked
        try {
            VentanaInternaClientes abrirVentanaInternaClientes = new VentanaInternaClientes();
            AbrirVentanaUnica objAbrirVentanaUnica = new AbrirVentanaUnica(jDesktopPane1);
            objAbrirVentanaUnica.VentanaActiva(abrirVentanaInternaClientes);
        } catch (Exception ex) {
            Logger.getLogger(VentanaMenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_IngresoClientesMouseClicked

    private void IngresoInventarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IngresoInventarioMouseClicked
        try {
            VentanaInternaInventarioPeliculas abrirVentanaInventarioPeliculas = new VentanaInternaInventarioPeliculas();
            AbrirVentanaUnica objAbrirVentanaUnica = new AbrirVentanaUnica(jDesktopPane1);
            objAbrirVentanaUnica.VentanaActiva(abrirVentanaInventarioPeliculas);
        } catch (Exception ex) {
            Logger.getLogger(VentanaMenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_IngresoInventarioMouseClicked

    private void IngresoReservacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IngresoReservacionMouseClicked
        try {
            VentanaInternaReservacionPeliculas abrirVentanaInternaReservacionPeliculas = new VentanaInternaReservacionPeliculas();
            AbrirVentanaUnica objAbrirVentanaUnica = new AbrirVentanaUnica(jDesktopPane1);
            objAbrirVentanaUnica.VentanaActiva(abrirVentanaInternaReservacionPeliculas);
        } catch (Exception ex) {
            Logger.getLogger(VentanaMenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_IngresoReservacionMouseClicked

    private void IngresoHistoricoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IngresoHistoricoMouseClicked
        try {
            VentanaInternaHistoricoPeliculasCliente abrirVentanaInternaHistoricoPeliculasCliente = new VentanaInternaHistoricoPeliculasCliente();
            AbrirVentanaUnica objAbrirVentanaUnica = new AbrirVentanaUnica(jDesktopPane1);
            objAbrirVentanaUnica.VentanaActiva(abrirVentanaInternaHistoricoPeliculasCliente);
        } catch (Exception ex) {
            Logger.getLogger(VentanaMenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_IngresoHistoricoMouseClicked

    private void IngresoDisponibilidadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IngresoDisponibilidadMouseClicked
        try {
            VentanaInternaDisponibilidadPeliculas abrirVentanaInternaDisponibilidadPeliculas = new VentanaInternaDisponibilidadPeliculas();
            AbrirVentanaUnica objAbrirVentanaUnica = new AbrirVentanaUnica(jDesktopPane1);
            objAbrirVentanaUnica.VentanaActiva(abrirVentanaInternaDisponibilidadPeliculas);
        } catch (Exception ex) {
            Logger.getLogger(VentanaMenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_IngresoDisponibilidadMouseClicked

    private void IngresoUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngresoUsuariosActionPerformed
        try {
            VentanaInternaUsuarios abrirVentanaInternaUsuarios = new VentanaInternaUsuarios();
            AbrirVentanaUnica objAbrirVentanaUnica = new AbrirVentanaUnica(jDesktopPane1);
            objAbrirVentanaUnica.VentanaActiva(abrirVentanaInternaUsuarios);
        } catch (Exception ex) {
            Logger.getLogger(VentanaMenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_IngresoUsuariosActionPerformed

    private void IngresoEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngresoEmpleadosActionPerformed
        try {
            VentanaInternaEmpleados abrirVentanaInternaEmpleados = new VentanaInternaEmpleados();
            AbrirVentanaUnica objAbrirVentanaUnica = new AbrirVentanaUnica(jDesktopPane1);
            objAbrirVentanaUnica.VentanaActiva(abrirVentanaInternaEmpleados);
        } catch (Exception ex) {
            Logger.getLogger(VentanaMenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_IngresoEmpleadosActionPerformed

    private void IngresoVacacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngresoVacacionesActionPerformed
        try {
            VentanaInternaVacaciones abrirVentanaInternaVacaciones = new VentanaInternaVacaciones();
            AbrirVentanaUnica objAbrirVentanaUnica = new AbrirVentanaUnica(jDesktopPane1);
            objAbrirVentanaUnica.VentanaActiva(abrirVentanaInternaVacaciones);
        } catch (Exception ex) {
            Logger.getLogger(VentanaMenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_IngresoVacacionesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaMenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fechalbl;
    private javax.swing.JLabel Horalbl;
    private javax.swing.JMenu IngresoClientes;
    private javax.swing.JMenu IngresoDisponibilidad;
    private javax.swing.JMenuItem IngresoEmpleados;
    private javax.swing.JMenu IngresoHistorico;
    private javax.swing.JMenu IngresoInventario;
    private javax.swing.JMenu IngresoRRHH;
    private javax.swing.JMenu IngresoReservacion;
    private javax.swing.JMenuItem IngresoUsuarios;
    private javax.swing.JMenuItem IngresoVacaciones;
    private javax.swing.JMenu OpcionSalir;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    // End of variables declaration//GEN-END:variables

}
