/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfazGrafica;

import CapaBL.UsuariosBL;
import CapaBL.VacacionesBL;
import Utilidades.FechaHora;
import Entidades.Usuarios;
import Entidades.Vacaciones;
import java.text.ParseException;
import java.text.SimpleDateFormat;

import java.util.Date;


/**
 *
 * @author Emma
 */
public class VentanaValidacion extends javax.swing.JFrame {

    UsuariosBL objUsuariosBL;
    int IntContadorBloqueado = 0;
    VacacionesBL objVacacionesBL;

    /**
     * Creates new form VentanaValidacion
     */
    public VentanaValidacion() {
        initComponents();
        objUsuariosBL = new UsuariosBL();
        objVacacionesBL = new VacacionesBL();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel3 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        Entrarbtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblErrorUsuario = new javax.swing.JLabel();
        lblUsuarioNoExiste = new javax.swing.JLabel();
        lblErrorPassword = new javax.swing.JLabel();
        lblContrasenaInvalida = new javax.swing.JLabel();
        lblErrorUnknown = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(410, 540));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel3.setFont(new java.awt.Font("AR BERKLEY", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Hitokiri");
        jDesktopPane1.add(jLabel3);
        jLabel3.setBounds(40, 120, 320, 60);
        jDesktopPane1.add(txtUsuario);
        txtUsuario.setBounds(130, 280, 150, 30);
        jDesktopPane1.add(txtPassword);
        txtPassword.setBounds(130, 380, 150, 30);

        Entrarbtn.setText("Entrar");
        Entrarbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EntrarbtnMouseClicked(evt);
            }
        });
        jDesktopPane1.add(Entrarbtn);
        Entrarbtn.setBounds(160, 460, 90, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Usuario");
        jDesktopPane1.add(jLabel2);
        jLabel2.setBounds(180, 250, 60, 20);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Contraseña");
        jDesktopPane1.add(jLabel1);
        jLabel1.setBounds(170, 350, 90, 20);

        lblErrorUsuario.setForeground(new java.awt.Color(255, 255, 255));
        lblErrorUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jDesktopPane1.add(lblErrorUsuario);
        lblErrorUsuario.setBounds(20, 320, 370, 20);

        lblUsuarioNoExiste.setForeground(new java.awt.Color(255, 255, 255));
        lblUsuarioNoExiste.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jDesktopPane1.add(lblUsuarioNoExiste);
        lblUsuarioNoExiste.setBounds(150, 220, 110, 30);

        lblErrorPassword.setForeground(new java.awt.Color(255, 255, 255));
        lblErrorPassword.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jDesktopPane1.add(lblErrorPassword);
        lblErrorPassword.setBounds(30, 420, 360, 20);

        lblContrasenaInvalida.setForeground(new java.awt.Color(255, 255, 255));
        lblContrasenaInvalida.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jDesktopPane1.add(lblContrasenaInvalida);
        lblContrasenaInvalida.setBounds(150, 500, 110, 30);

        lblErrorUnknown.setForeground(new java.awt.Color(255, 255, 255));
        jDesktopPane1.add(lblErrorUnknown);
        lblErrorUnknown.setBounds(50, 180, 300, 50);

        jLabel4.setFont(new java.awt.Font("AR BERKLEY", 1, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Video ");
        jDesktopPane1.add(jLabel4);
        jLabel4.setBounds(40, 60, 320, 60);

        getContentPane().add(jDesktopPane1);
        jDesktopPane1.setBounds(0, 0, 410, 540);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EntrarbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EntrarbtnMouseClicked
        try {
            ClearLabels();
            FechaHora objFechaHora = new FechaHora();
            String StrFechaSistema = objFechaHora.Fecha();
            Usuarios ItemUsuarios = null;
            Vacaciones ItemVacaciones = null;
            ItemUsuarios = objUsuariosBL.ConsultaPorID(txtUsuario.getText());
            if (ItemUsuarios != null) {
                //usuario existe
                System.out.println("Usuario existe");
                ItemVacaciones = objVacacionesBL.ConsultaPorID(ItemUsuarios.getIntIdempleado());
                String StrFechaArchivo = String.valueOf(ItemVacaciones.getClassFechaSolicitud().getIntDia()) + "/" + String.valueOf(ItemVacaciones.getClassFechaSolicitud().getIntMes()) + "/" + String.valueOf(ItemVacaciones.getClassFechaSolicitud().getIntAno());
                int IntDiasEntreFechas = ContarDias(StrFechaSistema,StrFechaArchivo);
                boolean bloqueado = ItemUsuarios.isBoolBloqueado();
                if (bloqueado != true) {
                    //no está bloqueado
                    System.out.println("Usuario no está bloqueado");
                    if (ItemUsuarios.getStrContrasena().equals(txtPassword.getText())) {
                        //contraseña hace match.
                        IntContadorBloqueado = 0;
                        if (IntDiasEntreFechas > ItemVacaciones.getIntCantidadDias()) {
                            //la fecha del sistema hace match con la fecha de solicitud del archivo
                            VentanaMenuPrincipal abrirVentanaMenuPrincipal = new VentanaMenuPrincipal();
                            abrirVentanaMenuPrincipal.setVisible(true);
                            this.setVisible(false);
                        } else {
                            lblErrorUsuario.setText("El usuario esta de vacaciones, no puede ingresar");
                        }
                    } else {
                        lblContrasenaInvalida.setText("Contraseña Invalida");
                        IntContadorBloqueado += 1;
                        if (IntContadorBloqueado <= 3) {
                            switch (IntContadorBloqueado) {
                                case 1:
                                    lblErrorPassword.setText("Le quedan 2 intentos antes de bloquear su usuario");
                                    break;
                                case 2:
                                    lblErrorPassword.setText("Le queda 1 intento antes de bloquear su usuario");
                                    break;
                                case 3:
                                    lblErrorPassword.setText("Su usuario ha sido bloqueado");
                                    ItemUsuarios.setBoolBloqueado(true);
                                    objUsuariosBL.Actualizar(ItemUsuarios);
                                    break;
                            }
                        }
                    }
                } else {
                    //usuario bloqueado
                    lblErrorUsuario.setText("Su usuario está bloqueado");
                }
            } else {
                //usuario no existe
                lblUsuarioNoExiste.setText("Usuario no existe");
            }
        } catch (Exception ex) {
            lblErrorUnknown.setText("Error al Inciar el programa");

        }
    }//GEN-LAST:event_EntrarbtnMouseClicked

    private void ClearLabels()
    {
        lblErrorPassword.setText("");
        lblErrorUsuario.setText("");
        lblUsuarioNoExiste.setText("");
        lblContrasenaInvalida.setText("");
    }
    
    private int ContarDias(String StrFechaSistema, String StrFechaArchivo) throws ParseException 
    {
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        Date fechaInicial = dateFormat.parse(StrFechaArchivo);
        Date fechaFinal = dateFormat.parse(StrFechaSistema);
        int ContadorDias = (int) ((fechaFinal.getTime()-fechaInicial.getTime())/86400000);
        return ContadorDias;
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaValidacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaValidacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaValidacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaValidacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaValidacion().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Entrarbtn;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblContrasenaInvalida;
    private javax.swing.JLabel lblErrorPassword;
    private javax.swing.JLabel lblErrorUnknown;
    private javax.swing.JLabel lblErrorUsuario;
    private javax.swing.JLabel lblUsuarioNoExiste;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
